### ISSUE TITLE
bug in PolygonArea

### ISSUE THREAD

**Issue by jimhanks** [PyxisInt/GeographicLib#1]
There is some kind of bug with the masking here:
https://github.com/PyxisInt/GeographicLib/blob/master/PyxisInt.GeographicLib/PolygonArea.cs#L100

I was able to hack enough of a debug session to tell that the g.GeodesicScale12 value was not getting computed inside the Inverse function. This is turn makes any subsequent calls to PolygonArea.Compute fails, i.e. sends back NaN for the area.

I was unable to dig deep enough to find the real culprit. But I did go back to the Java implementation and do my own C# port and it is giving back area answers as expected. I'd be happy to share that port but it doesn't diff well against these sources so I'm kinda at my limit for debugging here.

**Comment by ghosh9691** [comment]
Thanks! Will take a look
